### ISSUE TITLE
Add more words to the blocklist

### ISSUE THREAD

**Issue by fluaten** [Daggron/No-coronavirus#1]
Hi,
Really nice and simple addon, thanks for making it.
Could you add extra case ?

```
[cC][oO][rR][oO][nN][aA][vV][iI][rR][uU][sS]
[cC][oO][rR][oO][nN][aA] [vV][iI][rR][uU][sS]
[cC][oO][vV][iI][dD]19
[cC][oO][vV][iI][dD]\-19
[sS][aA][rR][sS]\-[cC][oO][vV][iI][dD]\-19
[sS][aA][rR][sS]\-[cC][oO][vV][iI][dD]\-19\-2
[sS][aA][rR][sS]\-[cC][oO][vV]\-2
2019\-[nN][cC][oO][vV]
```

or simply put this line

```
[cC][oO][rR][oO][nN][aA][vV][iI][rR][uU][sS]|[cC][oO][rR][oO][nN][aA] [vV][iI][rR][uU][sS]|[cC][oO][vV][iI][dD]19|[cC][oO][vV][iI][dD]\-19|[sS][aA][rR][sS]\-[cC][oO][vV][iI][dD]\-19|[sS][aA][rR][sS]\-[cC][oO][vV][iI][dD]\-19\-2|[sS][aA][rR][sS]\-[cC][oO][vV]\-2|2019\-[nN][cC][oO][vV]
```

[You can test on this page if something missing](https://en.wikipedia.org/wiki/Severe_acute_respiratory_syndrome_coronavirus_2)

**Comment by Daggron** [comment]
Thanks @fluaten i will surely look up to this.
Will release the new version with these changes soon

**Comment by ishandeveloper** [comment]
Can i work on this?

**Comment by fluaten** [comment]
Thanks for the update, unfortunately it now replace also words with "cov" in it, for example  : 
discovery -> dis░░█▒ █▒▒ █▓▓░very

The good regex is : 

`  element.textContent = element.textContent.replace(/[cC][oO][vV][iI][dD]\-19|[sS][aA][rR][sS]|[cC][oO][rR][oO][nN][aA][vV][iI][rR][uU][sS]|[cC][oO][rR][oO][nN][aA]|[vV][iI][rR][uU][sS]|[cC][oO][vV][iI][dD]|[sS][aA][rR][sS]\-[cC][oO][vV][iI][dD]\-19|[sS][aA][rR][sS]\-[cC][oO][vV][iI][dD]\-19\-2|[sS][aA][rR][sS]\-[cC][oO][vV]\-2|2019\-[nN][cC][oO][vV]|[cC][oO][vV]\-2/gi, '░░█▒ █▒▒ █▓▓░');`
